Repository carenalgas/popochiu, pull requests merged in 2024-10, with the labels that each got.

#296 Fix vframe calculation for Prop's current sprite frame
  addons/popochiu/engine/objects/prop/popochiu_prop.gd
Labels: improvement

#300 Feature: Show system text in queue when text does not contain colon
  addons/popochiu/engine/helpers/popochiu_characters_helper.gd
Labels: improvement, proposal

#313 Fixes #312: cutscene skip to black screen
  addons/popochiu/editor/config/config.gd
  addons/popochiu/engine/helpers/popochiu_characters_helper.gd
  addons/popochiu/engine/interfaces/i_room.gd
  addons/popochiu/engine/objects/character/popochiu_character.gd
  addons/popochiu/engine/objects/gui/components/system_text/system_text.gd
  addons/popochiu/engine/objects/popochiu_settings.gd
  addons/popochiu/engine/objects/transition_layer/images/bg.png
  addons/popochiu/engine/objects/transition_layer/transition_layer.gd
  addons/popochiu/engine/objects/transition_layer/transition_layer.tscn
  addons/popochiu/engine/popochiu.gd
Labels: bug
